services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - lamp-store-network

  # Backend services will be added later

  # Database services will be added later

networks:
  lamp-store-network:
    driver: bridge

# volumes:
#   postgres_data:
