services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - lamp-store-network
    volumes:
      - frontend_images:/usr/share/nginx/html/images

  products_service:
    build:
      context: ./products_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - products_postgres
    environment:
      - DB_HOST=products_postgres
      - DB_PORT=5432
      - DB_NAME=lamp_store
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - lamp-store-network
    volumes:
      - frontend_images:/usr/share/nginx/html/images

  products_postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lamp_store
    ports:
      - "5432:5432"
    volumes:
      - products_postgres_data:/var/lib/postgresql/data
      - ./products_service/migrations:/docker-entrypoint-initdb.d
      - ./products_service/migrations:/app/migrations
    networks:
      - lamp-store-network

  orders_service:
    build:
      context: ./orders_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - orders_postgres
      - products_service
    environment:
      - DB_HOST=orders_postgres
      - DB_PORT=5432
      - DB_NAME=lamp_store
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - lamp-store-network

  orders_postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lamp_store
    ports:
      - "5433:5432"
    volumes:
      - orders_postgres_data:/var/lib/postgresql/data
      - ./orders_service/migrations:/docker-entrypoint-initdb.d
      - ./orders_service/migrations:/app/migrations
    networks:
      - lamp-store-network

  admin_service:
    build:
      context: ./admin_service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - products_service
      - orders_service
    environment:
      - JWT_SECRET=your-secret-key
      - PRODUCTS_SERVICE_URL=http://products_service:8000
      - ORDERS_SERVICE_URL=http://orders_service:8001
    networks:
      - lamp-store-network

networks:
  lamp-store-network:
    driver: bridge

volumes:
  products_postgres_data:
  orders_postgres_data:
  frontend_images:
