version: '3.8'
services:
  orders_service:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - orders_postgres
    environment:
      - DB_HOST=orders_postgres
      - DB_PORT=5432
      - DB_NAME=lamp_store
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./migrations:/app/migrations
    networks:
      - lamp-store-network

  orders_postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lamp_store
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lamp-store-network

networks:
  lamp-store-network:
    driver: bridge

volumes:
  postgres_data: 