services:
  orders_service:
    build: .
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
    depends_on:
      - postgres
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lamp_store
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data: 