version: '3.8'

services:
  products_service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - products_postgres
    environment:
      - DB_HOST=products_postgres
      - DB_PORT=5432
      - DB_NAME=lamp_store
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./migrations:/app/migrations
      - frontend_images:/usr/share/nginx/html/images
    networks:
      - lamp-store-network

  products_postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lamp_store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lamp-store-network

  frontend:
    build: ../frontend
    ports:
      - "80:80"
    volumes:
      - frontend_images:/usr/share/nginx/html/images
    networks:
      - lamp-store-network

networks:
  lamp-store-network:
    driver: bridge

volumes:
  postgres_data:
  frontend_images: 